# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^secrets/|^appenv$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: trailing-whitespace
        exclude: |
          (?x)^(
            secrets/|environments/.*/secret.*|
            .*\.patch
          )$
    -   id: end-of-file-fixer
        exclude: |
          (?x)^(
            environments/.*/secret.*|
            .*\.patch
          )$
    -   id: check-yaml
        exclude: |
          (?x)^(
            environments/.*/secret.*|
            .*\.patch
          )$
    -   id: check-json
        exclude: |
          (?x)^(
            environments/.*/secret.*|
            .*\.patch
          )$
    -   id: check-xml
        exclude: |
          (?x)^(
            environments/.*/secret.*|
            .*\.patch
          )$
    -   id: check-toml
        exclude: |
          (?x)^(
            environments/.*/secret.*|
            .*\.patch
          )$

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      # ignore "line too long" [E501] and "imported but unused" [F401] (required for some batou functionality)
      args: [ "--ignore", "E501", "--ignore", "F401", "--fix"]
