#!/usr/bin/env bash

set -euxo pipefail

if [ -n "$(git status --porcelain)" ]; then
	echo "Unclean working directory, refusing to apply codestyle update."
	exit 1
fi

# http://mywiki.wooledge.org/BashFAQ/028
bundledir=${BASH_SOURCE%/*}
venv=${bundledir}/.venv

python3 -m venv $venv
$venv/bin/pip install -r $bundledir/requirements.txt

mkdir -p .github
cp -r ${bundledir}/github/* .github

$venv/bin/python $bundledir/merge-pre-commit-config.py \
	"${bundledir}/pre-commit-config.yaml" \
	.pre-commit-config.yaml

cp "${bundledir}/pyproject.toml" .


pre-commit install
pre-commit run -a
