#!/usr/bin/env bash

if [ -n "$(git status --porcelain)" ]; then
	echo "Unclean working directory, refusing to apply codestyle update."
	exit 1
fi

# http://mywiki.wooledge.org/BashFAQ/028
bundledir=${BASH_SOURCE%/*}/

cp "${bundledir}/.pre-commit-config.yaml" .
cp "${bundledir}/pyproject.toml" .

pre-commit install
pre-commit run -a
